### ISSUE TITLE
Passing --RemoteProcessProxy.port-range argument for yarn cluster mode

### ISSUE THREAD

**Issue by kkalugerov** [jupyter-incubator/enterprise_gateway#347] opened 2018-05-16 12:59 UTC
Hello guys,
Can you explain how should we pass "{port_range}" with command jupyter enterprisegateway --ip=0.0.0.0 :? Or should it be configured inside the kernel.json :?

I'm using version 0.9 of jupyter enterprisegateway

**Comment by kevin-bates** [comment] 2018-05-16 14:47
@kkalugerov - thank you for your question.

Curly-braced values within the `argv` stanza of the kernel.json file represent substitutable parameters that Enterprise Gateway injects prior to the invocation of the argument vector.  There are a couple places from which the value for `{port_range}` can derive.
1. If a port range is defined globally via either command line `--EnterpriseGatewayApp.port_range` or env `EG_PORT_RANGE` options, then this value will be used.  This option is referenced in the [Configuration Options](http://jupyter-enterprise-gateway.readthedocs.io/en/latest/config-options.html#configuration-options) section.
2. If the administrator prefers to split kernels by port range, then the port-range used by specific kernel-specs can be specified in the `config:` block of the `process_proxy:` stanza in the `kernel.json` file as described in [Process Proxy Configuration](http://jupyter-enterprise-gateway.readthedocs.io/en/latest/system-architecture.html#process-proxy-configuration).  If this approach is used, it overrides the global definition previously described.
3. Of course, the `{port_range}` value could be manually replaced in the `argv` stanza but that will circumvent some of the validation that Enterprise Gateway performs on the range values and is not recommended.

For completeness, since `0..0` is the default port-range value, and because the range is 0 in length, no port range is imposed by default.

**Comment by kkalugerov** [comment] 2018-05-16 15:00
Although I have specified it in kernel.json like this "--Remote Process Proxy.port-range","{40000..41000}" it always spawning new kernels again and again... and they finishin even without did any job...
This is my kernel.json
{ 
 "language": "python",
  "display_name": "Spark - Python (YARN Client Mode)",
  "process_proxy": {
    "class_name": "enterprise_gateway.services.processproxies.yarn.YarnClusterProcessProxy"
  },
  "env": {
    "SPARK_HOME": "/usr/local/spark-2.1.2-bin-hadoop2.7",
    "PYSPARK_PYTHON": "/tmp/yes/bin/python",
    "PYTHONPATH": "/tmp/yes/lib/python3.6/site-packages:/usr/local/spark-2.1.2-bin-hadoop2.7/python:/usr/local/spark-2.1.2-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip",
    "SPARK_OPTS": "--master yarn --deploy-mode cluster --name ${KERNEL_ID:-ERROR__NO__KERNEL_ID} --conf spark.yarn.submit.waitAppCompletion=false --conf spark.yarn.appMasterEnv.PYTHONUSERBASE=/home/yarn/.l$
    "LAUNCH_OPTS": ""
  },
  "argv": [
    "/usr/local/share/jupyter/kernels/spark_python_yarn_cluster/bin/run.sh",
    "{connection_file}",
    "--RemoteProcessProxy.response-address",
    "{response_address}",
    "--RemoteProcessProxy.port-range",
    "{40000..41000}",
    "--RemoteProcessProxy.spark-context-initialization-mode",
    "lazy"
  ]
}

**Comment by kevin-bates** [comment] 2018-05-16 17:25
Right - the curly-braces represent meta-characters that inform EG that its a substitution and `port_range` is the context.  As a result, the curly-braces should not be part of the value.   

Please try without the braces (e.g., `40000..41000`).  However, as mentioned above, its better practice to revert the argv stanza entry back to `{port_range}` and change the process_proxy stanza to...
```json
"process_proxy": {
    "class_name": "enterprise_gateway.services.processproxies.yarn.YarnClusterProcessProxy",
    "config": {
      "port_range": "40000..41000"
    }
```
Or use the globally-scoped form (i.e., EG command-line or environment variable).

**Comment by kkalugerov** [comment] 2018-05-17 07:06
I have tried with your example also but... the problem is that when I start the gateway with this kernel which I have shown you and then I start the jupyter notebook and open just one new notebook with Spark Yarn Cluster kernel it starts to spawning new kernels all the time just with one single notebook opened and all the kernels are dying just a few seconds after starting new yarn application process...:\

**Comment by kkalugerov** [comment] 2018-05-17 07:40
https://www.dropbox.com/s/i2oytedzr2jwlav/Screenshot%20from%202018-05-17%2010-13-16.png?dl=0
This is what I'm talking about... Spawning new yarn applications which freeze on ACCEPTED state and only one is on RUNNING state.

**Comment by kevin-bates** [comment] 2018-05-17 14:09
@kkalugerov, I will defer to @lresende for your `PYTHONUSERBASE` question above.

The jupyter framework will automatically attempt kernel restarts if it detects that it did not startup correctly, or has died after startup.  So, the looping indicates that the kernel is not completing its startup.

After looking at the log, I get the impression you're not going through Enterprise Gateway to launch the kernel.  EG is responsible for setting up the `KERNEL_ID` variable and I'm not sure I've ever seen that not happen (although that would be the case if you were, say, attempting to use one of these kernelspecs from general Notebook).  In fact, the kernel-info-timeout warning at 8:53:21 shows just that - `NotebookApp`.  

To use Enterprise Gateway with a Notebook, you must install the NB2KG extension on your Notebook server.  You then set a `KG_URL` environment variable to point at the Enterprise Gateway server, where EG is running and the kernelspecs have been installed.  The kernelspecs will be remote from the Notebook server.  Only the notebook files themselves reside on the NB server.  Please refer to the [Getting Started](http://jupyter-enterprise-gateway.readthedocs.io/en/latest/getting-started.html) page for additional information.

Once you get Enterprise Gateway running and if you still have issues, please provide the EG log with DEBUG tracing enabled (`--log-level=DEBUG`).

I see that you circled the `Shutdown hook called` log entry.  This is normal.  When using YARN cluster mode, we want the script that calls spark-submit to be stopped.  At that point, the kernel (and its corresponding launcher) are running on a worker node within the cluster - no reason to keep that process running.

**Comment by kkalugerov** [comment] 2018-05-17 14:33
I followed your instructions and set the nb2kg set the needed url pointing to the gateway but when I try to create new notebook with spark on clustered yarn it gives me this error :
`Traceback (most recent call last):
  File "/tmp/yes/lib/python3.6/site-packages/tornado/web.py", line 1512, in _execute
    result = yield result
  File "/tmp/yes/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/tmp/yes/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/tmp/yes/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/tmp/yes/lib/python3.6/site-packages/notebook/services/sessions/handlers.py", line 73, in post
    type=mtype))
  File "/tmp/yes/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/tmp/yes/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/tmp/yes/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/tmp/yes/lib/python3.6/site-packages/nb2kg/managers.py", line 333, in create_session
    session_id, path, name, type, kernel_name,
  File "/tmp/yes/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/tmp/yes/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/tmp/yes/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/tmp/yes/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/tmp/yes/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/tmp/yes/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/tmp/yes/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/tmp/yes/lib/python3.6/site-packages/nb2kg/managers.py", line 145, in start_kernel
    response = yield fetch_kg(self.kernels_endpoint, method='POST', body=json_body)
  File "/tmp/yes/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/tmp/yes/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/tmp/yes/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/tmp/yes/lib/python3.6/site-packages/nb2kg/managers.py", line 64, in fetch_kg
    response = yield client.fetch(url, **kwargs)
  File "/tmp/yes/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/tmp/yes/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
tornado.httpclient.HTTPError: HTTP 500: Internal Server Error
`

**Comment by kkalugerov** [comment] 2018-05-17 15:19
Ok we have got some progress but now when I create a notebook with the spark-yarn-cluster kernel this is happening :
https://www.dropbox.com/s/sjx2hhule4ct3ig/Screenshot%20from%202018-05-17%2018-13-04.png?dl=0

**Comment by kevin-bates** [comment] 2018-05-17 15:37
Glad to see there's progress.  You should check the YARN logs for application `xxx_0115`.  I suspect the `stdout` log will contain an issue regarding the parameters to the launcher or a dependency issue or something to that affect.

Luckily, it looks like the very first line of your image (again a **file** would be significantly more helpful) shows only a single `.` between the lower and upper port range values (`40000.41000`).  Of course, I can't determine if that's a resolution issue with the image or not.

So, if I had to guess what the issue is, its an argument parse error due to there not being two dots separating the range values (e.g., `40000..41000`).

**Comment by lresende** [comment] 2018-05-17 17:33
Your error log also shows that YARN seems to be running out of resources

![yarn-resource-issues](https://user-images.githubusercontent.com/382917/40193919-9c765c94-59bd-11e8-924a-3262695b3fba.png)

**Comment by kkalugerov** [comment] 2018-05-18 13:01
@kevin-bates Thank you for the time I finally managed to run it now I just have to configure spark-defaults for proper distribution of resources.

**Comment by kevin-bates** [comment] 2018-05-18 13:43
Great news @kkalugerov - welcome to Jupyter Enterprise Gateway!

I'm going to close this issue.  Please feel free to open others and/or make contributions.

**Closed by kevin-bates** 2018-05-18 13:43 UTC
Labels: Question
