### ISSUE TITLE
JEG kernels cannot be found as "Running" in Jupyter notebook

### ISSUE THREAD

**Issue by charlieeeeeee** [jupyter-incubator/enterprise_gateway#282] opened 2018-03-20 20:11 UTC
Steps to reproduce:
1) Launch notebook and JEG
2) Start remote kernel (Kernel is started and responsive)
3) While the kernels are still alive and running. Navigate to the main menu and observe the notebook icon is **not GREEN** (which suppose to be green, to show active/running kernel)
4) Verify this by clicking on the "Running" tab. No running notebook is found.

Here are attached images of when issue occur for reference.

![5662ad78c09a4d14](https://user-images.githubusercontent.com/37548682/37680009-08ecac08-2c59-11e8-983f-b2c081547869.jpg)
![bb73ce0619484c4](https://user-images.githubusercontent.com/37548682/37680010-0905981c-2c59-11e8-9c5d-79c626f20acb.jpg)

**Comment by kevin-bates** [comment] 2018-03-20 21:39
Thanks @charlieeeeeee .  I spent some time with this and found it also occurs with "local" kernels (i.e., kernels that are local to JEG).  I also found this to occur with the latest release of JKG.  So I'm now a little suspicious that this is a client-side issue (with Notebook/nb2kg) but still need to take a closer look.

**Comment by kevin-bates** [comment] 2018-03-24 00:32
Well, it appears as though somewhere between Notebook `4.3.1` and `5.2.1` this functionality broke.  I haven't tried any versions in between these two but have confirmed that in `4.3.1` the following is produced:
![screen shot 2018-03-23 at 5 26 04 pm](https://user-images.githubusercontent.com/22599560/37858234-908d83d6-2ebf-11e8-9ca7-a9ffd627803b.png)
while in versions later than `5.2.1` (and perhaps earlier), the running kernels do not show up.

As a result, this should be deemed a Notebook issue and I'm marking as `Invalid` relative to Enterprise Gateway.

**Closed by kevin-bates** 2018-03-24 00:32 UTC
Labels: Invalid

**Comment by kevin-bates** [comment] 2018-03-24 00:43
Hmm - I just ran a pure Notebook (no nb2kg) and found that things work correctly and this is using `5.4.0`.  As a result, this implies that its something in the NB stack and possibly affected by the nb2kg extension (sigh).  

I'm still leaving this issue closed relative to EG.  This latest info just means that Notebook isn't necessarily the location to be poking around.

**Comment by charlieeeeeee** [comment] 2018-03-24 17:11
@kevin-bates Right. I noticed the same behavior your comment regarding to "non-nb2kg" scenario.

**Comment by kevin-bates** [comment] 2018-03-24 20:15
Spent another 4 hours on this today and it seems like there must be something in the notebook in later releases that is side-affected when nb2kg is installed.  However, in BOTH cases (older vs. newer NB versions), I find all the correct methods to return the list of running kernels getting called in nb2kg.  Since these pages are a function of the js files, I suspect it's something within there - but don't know java script well enough to really tie the two (js and python) together.

**Comment by kevin-bates** [comment] 2018-03-25 18:12
After narrowing this down, I found that the issue was introduced in Notebook `5.1.0.rc1` (Notebook `5.0.0` behaves fine).  Looking at the various changes, it looks like this [PR](https://github.com/jupyter/notebook/pull/2559) is where things get messed up for nb2kg because it doesn't return the `type` column from `row_to_model()` and that PR now discriminates on that value.

I will open an issue in NB2KG and apply the fix there.

cc: @charlieeeeeee
